Added key features of Augurk to the public website
Augurk/augurk.github.io pull request #2
Opened 2016-11-27 09:40 UTC by jmezach

Fixes #1

2016-11-28 06:24 UTC, marktaling requested changes

2016-11-28 06:24 UTC, marktaling commented on .gitignore
> +Thumbs.db
This seems to be a windows "feature"...
Probably better to ignore it?

2016-11-28 06:24 UTC, marktaling commented on index.html
> +                                    <strong><a href="https://github.com/Augurk/Augurk/releases/tag/1.0.0">September 2015</a>
Why should the date link to the same version?

2016-11-28 06:24 UTC, marktaling commented on index.html
> +                                Need to put some more style into your documentation? No problem, Augurk supports Markdown for
Perhaps: Need a bit more than just flat text for your documentation?

2016-11-28 06:24 UTC, marktaling commented on index.html
> +                                large tables so you can stay focused on the functionality. You can even collapse entire scenario's
scenarios

2016-11-28 06:24 UTC, marktaling commented on index.html
> +                                When pulling together all your feature files you need to be able to organise them. Augurk allows
When publishing all your feature files to a single location, things tend to get quite messy. Augurk helps you to prevent this by allowing you to organise your features into products and groups.

As for organize/organise, we should come to a decision whether we will use US or UK spelling for this site...

2016-11-28 06:24 UTC, marktaling commented on index.html
> +                                you to do this by organising them into products and groups. It even supports (semantic) versioning
In addition, it supports (semantic) versioning...

2016-11-28 06:24 UTC, marktaling commented on index.html
> +                                so you can view different versions of a particular feature all in one central place.
place seems a little Dutch for me. Location?

2016-11-28 06:24 UTC, marktaling commented on index.html
> +                                feature has not yet been fully implemented.
Instead of the error that will be displayed when you only use the ignore tag

2016-11-28 06:24 UTC, marktaling commented on index.html
> +                                Very soon we will enable support in Augurk for creating introduction pages for the various products.
In the near feature?

2016-11-28 06:24 UTC, marktaling commented on index.html
> +                                This gives you a landing page for your products as well as an entry-point for discovering the features
This allows to create a custom landing page...

2016-11-28 06:42 UTC, jmezach commented on .gitignore
> +Thumbs.db
Yeah, Windows generates that file. Shouldn't be in our repo.

2016-11-28 06:46 UTC, jmezach commented on index.html
> +                                    <strong><a href="https://github.com/Augurk/Augurk/releases/tag/1.0.0">September 2015</a>
Because that's the date we released it? It's not the greatest thing I know. Got any other suggestions for what we should put there?

2016-11-28 06:50 UTC, jmezach commented on index.html
> +                                When pulling together all your feature files you need to be able to organise them. Augurk allows
Agreed ;). Perhaps US English is best? I changed it to organize for now.

2016-11-28 06:55 UTC, jmezach commented on index.html
> +                                Very soon we will enable support in Augurk for creating introduction pages for the various products.
I hink you mean "In the near future"?

2016-11-28 06:56 UTC, jmezach commented on index.html
> +                                This gives you a landing page for your products as well as an entry-point for discovering the features
Perhaps "This allows for the creation of a custom landing page"?

2016-11-28 09:10 UTC, marktaling commented on index.html
> +                                    <strong><a href="https://github.com/Augurk/Augurk/releases/tag/1.0.0">September 2015</a>
I don't realy dislike the mention of the date. I dislike the double link. It suggests two different navigation paths while they point to the same resource.

2016-11-28 09:13 UTC, jmezach commented on index.html
> +                                    <strong><a href="https://github.com/Augurk/Augurk/releases/tag/1.0.0">September 2015</a>
We could remove the link altogether and just have the date there as text?

2016-11-28 09:25 UTC, marktaling commented on index.html
> +                                    <strong><a href="https://github.com/Augurk/Augurk/releases/tag/1.0.0">September 2015</a>
Works for me.

2016-11-29 06:50 UTC, marktaling approved these changes

2016-11-29 06:51 UTC, merged